### ISSUE TITLE
Import process at every program start

### ISSUE THREAD

**Issue by Valentin-Kaiser** [Plaenkler/GoST#35]
The import process is executed at every programme start, regardless of the interval or whether data is already available. In my opinion, the import should only be executed at the very first programme start if no data is available or if it is explicitly requested.

Is there a specific reason for this?

**Comment by Plaenkler** [comment]
There is no particular reason. I will create a configuration option.

**Comment by Plaenkler** [comment]
fd8f7404e3b35836ff0d7fcd3b05654b8a6a1d1d Is going to close this issue
