### ISSUE TITLE
Numbers of the (free) payment terms in configuration

### ISSUE THREAD

**Issue by Plaenkler** [Plaenkler/GoST#4]
Payment terms can have **different** numbers in each instance of the system, as they are created individually. It is crucial to distinguish between warranty cases and invoices subject to charges. It must therefore be possible to specify the corresponding numbers in the configuration.

**Comment by Valentin-Kaiser** [comment]
The payment conditions could be read from the table and then displayed in the frontend, the user then selects the appropriate condition so that guarantee invoices can then be identified.

**Comment by Plaenkler** [comment]
> The payment conditions could be read from the table and then displayed in the frontend, the user then selects the appropriate condition so that guarantee invoices can then be identified.

Good proposal will be implemented
