### ISSUE TITLE
Direct start of the web server when launching the application

### ISSUE THREAD

**Issue by Valentin-Kaiser** [Plaenkler/GoST#40]
Currently, the web server does not start until the application has completed the import process, would it be possible to start the web server directly and then display the status of the import process?

Something like: `Data is being imported` or maybe even more precise with a percentage.

**Comment by Plaenkler** [comment]
The import process now runs in a separate routine, so the web server starts as good as directly. b90dd6ddef83d195bf22068931826317367cef97
